---
title: "Unemployment and income in Germany - Case study"
output: github_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
if(!is.null(dev.list())) dev.off()
cat("\014")
```

# Loading necessary libraries

```{r}
library(eurostat)
library(rgdal)
library(sp)
library(spdep)
library(tidyverse)
```

```{r}
search_eurostat("unemployment") %>%
  arrange(desc(`last update of data`)) %>%
  head(10)
```


# Now get the data
```{r}
gdp <- get_eurostat("nama_10r_2gdp") %>%
  subset(grepl("DE([0-9]|[A-Z]){2}", geo))%>%
  filter(time == "2018-01-01", unit == "EUR_HAB")

unemp <- get_eurostat("lfst_r_lfu3rt") %>%
  subset(grepl("DE([0-9]|[A-Z]){2}", geo))%>%
  filter(time == "2018-01-01", unit == "PC", sex == "T", age == "Y15-74")

hh_inc <- get_eurostat("nama_10r_2hhinc")
gva_grwth <- get_eurostat("nama_10r_2gvagr")


```
```{r}
map <- readOGR(".",'NUTS_RG_10M_2016_4326_LEVL_2') %>%
  spTransform("+proj=longlat")

#Germany
map <-map[map@data$CNTR_CODE %in% "DE",]
```

```{r}
plot(map)
```








